/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.kiosk;

import java.awt.print.PrinterException;
import java.text.MessageFormat;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author User
 */
public class Kiosk extends javax.swing.JFrame {

    ComboMeals[][] meals = new ComboMeals[3][3];
    double total, price;
    String meal; 
   
    public void initMeals(){
        meals[0][0] = new ComboMeals("Burger", 200.00);  
        meals[0][1] = new ComboMeals("Fries",75.00);
        meals[1][0] = new ComboMeals("Nuggets",170.00);
        meals[1][1] = new ComboMeals("Chicken",150.00);
        meals[2][0] = new ComboMeals("Sundae",55.00);
        meals[2][1] = new ComboMeals("Coffee",95.00);
        
        
    }
    /**
     * Creates new form Kiosk
     */
    public Kiosk() {
        initComponents();
        initMeals();
        setLocationRelativeTo(null);
        txtReceipt.append("Welcome to Mcdolibee. \nThank you for your purchase!");
      
    }
    
    void clicked(int x, int y, JButton button){
        
        SpinnerNumberModel sModel = new SpinnerNumberModel(1, 1, 30, 1);
        JSpinner spinner = new JSpinner(sModel);
        int qty = 0; 
        
      
        if (button.getModel().isPressed()==true){     
        
    } else {
        JOptionPane.showMessageDialog(null, spinner, 
                meals[x][y].getName() + " ₱" + meals[x][y].getPrice(), 
                JOptionPane.INFORMATION_MESSAGE, button.getIcon());
       
        
        qty = (Integer)spinner.getValue();
        txtReceipt.append("\n" +qty+ " " + meals[x][y].getName()+"......................"+meals[x][y].getPrice()*qty);
        price = meals[x][y].getPrice()*qty;
        total += price;   
        }
       
    }
       
 
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnBurger = new javax.swing.JButton();
        btnFries = new javax.swing.JButton();
        btnNuggets = new javax.swing.JButton();
        btnChicken = new javax.swing.JButton();
        btnSundae = new javax.swing.JButton();
        btnCoffee = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReceipt = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnDone = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mcdonald's Kiosk");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(3, 2, 10, 10));

        btnBurger.setBackground(new java.awt.Color(255, 102, 102));
        btnBurger.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnBurger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/kiosk/src/1.png"))); // NOI18N
        btnBurger.setText("Burger ₱200");
        btnBurger.setDefaultCapable(false);
        btnBurger.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBurger.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBurgerActionPerformed(evt);
            }
        });
        jPanel1.add(btnBurger);

        btnFries.setBackground(new java.awt.Color(255, 102, 102));
        btnFries.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnFries.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/kiosk/src/2.png"))); // NOI18N
        btnFries.setText("Fries ₱75");
        btnFries.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFries.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFriesActionPerformed(evt);
            }
        });
        jPanel1.add(btnFries);

        btnNuggets.setBackground(new java.awt.Color(255, 102, 102));
        btnNuggets.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnNuggets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/kiosk/src/3.png"))); // NOI18N
        btnNuggets.setText("Nuggets ₱170");
        btnNuggets.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuggets.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuggets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuggetsActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuggets);

        btnChicken.setBackground(new java.awt.Color(255, 102, 102));
        btnChicken.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnChicken.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/kiosk/src/4.png"))); // NOI18N
        btnChicken.setText("Chicken ₱150");
        btnChicken.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChicken.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChickenActionPerformed(evt);
            }
        });
        jPanel1.add(btnChicken);

        btnSundae.setBackground(new java.awt.Color(255, 102, 102));
        btnSundae.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnSundae.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/kiosk/src/5.png"))); // NOI18N
        btnSundae.setText(" Sundae ₱55");
        btnSundae.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSundae.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSundae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSundaeActionPerformed(evt);
            }
        });
        jPanel1.add(btnSundae);

        btnCoffee.setBackground(new java.awt.Color(255, 102, 102));
        btnCoffee.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnCoffee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/kiosk/src/6.png"))); // NOI18N
        btnCoffee.setText("Coffee ₱95");
        btnCoffee.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCoffee.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoffeeActionPerformed(evt);
            }
        });
        jPanel1.add(btnCoffee);

        txtReceipt.setEditable(false);
        txtReceipt.setColumns(10);
        txtReceipt.setLineWrap(true);
        txtReceipt.setRows(5);
        jScrollPane1.setViewportView(txtReceipt);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/kiosk/src/logo.png"))); // NOI18N

        btnCancel.setBackground(new java.awt.Color(255, 51, 0));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnDone.setBackground(new java.awt.Color(0, 204, 0));
        btnDone.setForeground(new java.awt.Color(255, 255, 255));
        btnDone.setText("Done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 0));
        jLabel2.setText("SPECIALS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 315, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDone, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(341, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDone, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(106, 106, 106)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(41, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
       txtReceipt.append("\n \n Total Bill:  " + total);
        
        try {
            MessageFormat header = new MessageFormat("Mcdolibee");
            MessageFormat footer = new MessageFormat("Mcdolibee");
            
            boolean complete = txtReceipt.print(header, footer);
            if(complete){
                JOptionPane.showMessageDialog(null, "Done!", 
                        
                        "Information", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Printing", 
                        "Printer", JOptionPane.INFORMATION_MESSAGE);
                
            } 
        } catch (PrinterException e){
            JOptionPane.showMessageDialog(null, e);
        }
      
    }//GEN-LAST:event_btnDoneActionPerformed

    private void btnBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBurgerActionPerformed
           clicked(0,0, btnBurger);
    }//GEN-LAST:event_btnBurgerActionPerformed

    private void btnFriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFriesActionPerformed
            clicked(0,1, btnFries);
    }//GEN-LAST:event_btnFriesActionPerformed

    private void btnNuggetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuggetsActionPerformed
            clicked(1,0, btnNuggets);
    }//GEN-LAST:event_btnNuggetsActionPerformed

    private void btnChickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChickenActionPerformed
            clicked(1,1, btnChicken);
    }//GEN-LAST:event_btnChickenActionPerformed

    private void btnSundaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSundaeActionPerformed
            clicked(2,0, btnSundae);
    }//GEN-LAST:event_btnSundaeActionPerformed

    private void btnCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoffeeActionPerformed
            clicked(2,1, btnCoffee);
    }//GEN-LAST:event_btnCoffeeActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        txtReceipt.setText(null);
        txtReceipt.append("Welcome to Mcdolibee. \nThank you for your purchase!");
        total = 0;
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kiosk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kiosk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kiosk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kiosk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kiosk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBurger;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChicken;
    private javax.swing.JButton btnCoffee;
    private javax.swing.JButton btnDone;
    private javax.swing.JButton btnFries;
    private javax.swing.JButton btnNuggets;
    private javax.swing.JButton btnSundae;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtReceipt;
    // End of variables declaration//GEN-END:variables
}
